name: 'Dependency Review'
on: [pull_request]

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3.1.0
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v2
